<?php

/**
 * @file
 * Contains nkh_resource_migrate.module routing and help information.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function nkh_resource_migrate_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the nkh_resource_migrate module.
    case 'help.page.nkh_resource_migrate':
      $output = '';
      $output .= '<h2>' . t('About') . '</h2>';
      $output .= '<p>' . t('This module aims to be a starting point for any Drupal 8 migration.') . '</p>';
      $output .= '<h3>' . t('Helpful Links') . '</h3>';
      $output .= '<ul>';
      $output .= '<li><a href="/admin/config/development/configuration/single/import"' . t('Update Config Sync Files') . '</li>';
      $output .= '</ul>';
      return $output;

  }
}

/**
 * Implements hook_migration_plugins_alter().
 */
function nkh_resource_migrate_migration_plugins_alter(&$definitions) {
  $definitions['resource']['source']['path'] =
    drupal_get_path('module', 'nkh_resource_migrate') . $definitions['resource']['source']['path'];
  $definitions['resource_file']['source']['path'] =
    drupal_get_path('module', 'nkh_resource_migrate') . $definitions['resource_file']['source']['path'];
}
